# Generated by Django 4.1.3 on 2022-11-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["-created"], name="budgets_bud_created_dd9b5a_idx"
            ),
        ),
    ]
